//go:build linux

package kernel

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"

	"pigate/internal/model"

	"github.com/godbus/dbus/v5"
)

type RealDhcpManager struct {
	configPath     string
	baseConfigPath string
}

func NewRealDhcpManager() *RealDhcpManager {
	return &RealDhcpManager{
		configPath:     "/etc/dnsmasq.d/pigate-dhcp.conf",
		baseConfigPath: "/etc/dnsmasq.d/pigate-base.conf",
	}
}

// ensureBaseConfig writes basic dnsmasq configuration if it doesn't exist
func (m *RealDhcpManager) ensureBaseConfig() error {
	// Create directory if not exists
	if err := os.MkdirAll("/etc/dnsmasq.d", 0755); err != nil {
		return fmt.Errorf("failed to create dnsmasq.d directory: %w", err)
	}

	// Always write/refresh base config to ensure it has bind-interfaces
	content := `# /etc/dnsmasq.d/pigate-base.conf — Generated by PiGate
domain=pigate.local
expand-hosts
dhcp-authoritative
bind-interfaces
`
	if err := os.WriteFile(m.baseConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write dnsmasq base config: %w", err)
	}
	return nil
}

// validateDnsmasqConfig checks configuration syntax using dnsmasq --test
func (m *RealDhcpManager) validateDnsmasqConfig(tempFile string) error {
	cmd := exec.Command("dnsmasq", "--test", "--conf-file="+tempFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("dnsmasq config validation failed: %s (err: %w)", string(output), err)
	}
	return nil
}

// ApplyConfig writes config to temp file, validates it, and writes to real config path.
func (m *RealDhcpManager) ApplyConfig(cfgs []model.DhcpConfig, reservations []model.DhcpReservation) error {
	log.Printf("[DHCP Server] ApplyConfig called with %d configs and %d reservations", len(cfgs), len(reservations))

	if err := m.ensureBaseConfig(); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# /etc/dnsmasq.d/pigate-dhcp.conf — Generated by PiGate\n\n")

	for _, cfg := range cfgs {
		if !cfg.Enabled {
			continue
		}

		// Verify if interface exists in the OS
		if _, err := os.Stat("/sys/class/net/" + cfg.Interface); os.IsNotExist(err) {
			log.Printf("[DHCP Server] Interface %s does not exist in OS, skipping config", cfg.Interface)
			continue
		}

		sb.WriteString(fmt.Sprintf("# Configuration for interface: %s\n", cfg.Interface))
		sb.WriteString(fmt.Sprintf("interface=%s\n", cfg.Interface))

		leaseTimeStr := "24h"
		if cfg.LeaseTime > 0 {
			leaseTimeStr = fmt.Sprintf("%ds", cfg.LeaseTime)
		}

		sb.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n", cfg.Interface, cfg.StartIP, cfg.EndIP, leaseTimeStr))

		if cfg.Gateway != "" {
			sb.WriteString(fmt.Sprintf("dhcp-option=%s,3,%s\n", cfg.Interface, cfg.Gateway))
		}

		if cfg.DNS1 != "" {
			if cfg.DNS2 != "" {
				sb.WriteString(fmt.Sprintf("dhcp-option=%s,6,%s,%s\n", cfg.Interface, cfg.DNS1, cfg.DNS2))
			} else {
				sb.WriteString(fmt.Sprintf("dhcp-option=%s,6,%s\n", cfg.Interface, cfg.DNS1))
			}
		}
		sb.WriteString("\n")
	}

	// Add Static IP reservations
	if len(reservations) > 0 {
		sb.WriteString("# Static IP Reservations\n")
		for _, res := range reservations {
			if res.MacAddress != "" && res.IPAddress != "" {
				name := res.DeviceName
				if name == "" {
					name = "pigate-device"
				}
				// Remove spaces from hostname to satisfy dnsmasq syntax
				name = strings.ReplaceAll(name, " ", "-")
				sb.WriteString(fmt.Sprintf("dhcp-host=%s,%s,%s\n", res.MacAddress, res.IPAddress, name))
			}
		}
	}

	configData := sb.String()

	// Write to temp file for validation
	tempFile := "/tmp/pigate-dhcp-test.conf"
	if err := os.WriteFile(tempFile, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write temp config file: %w", err)
	}
	defer os.Remove(tempFile)

	// Validate syntax
	if err := m.validateDnsmasqConfig(tempFile); err != nil {
		return err
	}

	// Save to production
	if err := os.WriteFile(m.configPath, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write production dnsmasq dhcp config: %w", err)
	}

	log.Println("[DHCP Server] Config applied and validated successfully")
	return m.ReloadConfig()
}

func (m *RealDhcpManager) ReloadConfig() error {
	return RestartServiceViaDBus("dnsmasq.service")
}

func (m *RealDhcpManager) GetActiveLeases() ([]model.ActiveDhcpLease, error) {
	filePath := "/var/lib/misc/dnsmasq.leases"
	data, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return []model.ActiveDhcpLease{}, nil
		}
		return nil, fmt.Errorf("failed to read dnsmasq leases file: %w", err)
	}

	var leases []model.ActiveDhcpLease
	lines := strings.Split(string(data), "\n")
	for idx, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 4 {
			continue
		}

		expiryUnixStr := fields[0]
		mac := fields[1]
		ip := fields[2]
		hostname := fields[3]
		if hostname == "*" {
			hostname = "Unknown"
		}

		expiresAt := ""
		expiresIn := "Active (Real)"
		if expiryUnix, err := parseUnixTime(expiryUnixStr); err == nil {
			expiresAt = expiryUnix.Format(time.RFC3339)
			duration := time.Until(expiryUnix)
			if duration > 0 {
				hours := int(duration.Hours())
				mins := int(duration.Minutes()) % 60
				expiresIn = fmt.Sprintf("%d hours, %d mins", hours, mins)
			} else {
				expiresIn = "Expired"
			}
		}

		leases = append(leases, model.ActiveDhcpLease{
			ID:         fmt.Sprintf("lease-real-%d", idx),
			IPAddress:  ip,
			MacAddress: mac,
			Hostname:   hostname,
			ExpiresIn:  expiresIn,
			ExpiresAt:  expiresAt,
		})
	}
	return leases, nil
}

func parseUnixTime(secStr string) (time.Time, error) {
	var sec int64
	_, err := fmt.Sscanf(secStr, "%d", &sec)
	if err != nil {
		return time.Time{}, err
	}
	return time.Unix(sec, 0), nil
}

func (m *RealDhcpManager) WatchLeases(ctx context.Context, callback func(event string, lease model.ActiveDhcpLease)) error {
	conn, err := dbus.SystemBus()
	if err != nil {
		return fmt.Errorf("failed to connect to D-Bus system bus: %w", err)
	}

	// Add match rule to catch uk.org.thekelleys.dnsmasq signals
	call := conn.BusObject().Call("org.freedesktop.DBus.AddMatch", 0,
		"type='signal',sender='uk.org.thekelleys.dnsmasq',interface='uk.org.thekelleys.dnsmasq'")
	if call.Err != nil {
		return fmt.Errorf("failed to add match rule for dnsmasq signals: %w", call.Err)
	}

	c := make(chan *dbus.Signal, 20)
	conn.Signal(c)

	log.Println("[DHCP Server] Started D-Bus lease watcher for dnsmasq")

	for {
		select {
		case <-ctx.Done():
			log.Println("[DHCP Server] D-Bus lease watcher stopped")
			return nil
		case sig := <-c:
			log.Printf("[DHCP Server] Received D-Bus signal: %s", sig.Name)

			var event string
			if strings.HasSuffix(sig.Name, ".DhcpLeaseAdded") {
				event = "added"
			} else if strings.HasSuffix(sig.Name, ".DhcpLeaseUpdated") {
				event = "updated"
			} else if strings.HasSuffix(sig.Name, ".DhcpLeaseDeleted") {
				event = "deleted"
			} else {
				continue
			}

			var ip, mac, hostname string
			if len(sig.Body) >= 3 {
				val0, ok0 := sig.Body[0].(string)
				val1, ok1 := sig.Body[1].(string)
				val2, ok2 := sig.Body[2].(string)
				if ok0 && ok1 && ok2 {
					// Identify MAC and IP
					if strings.Contains(val0, ":") || strings.Contains(val0, "-") {
						mac = val0
						ip = val1
					} else {
						ip = val0
						mac = val1
					}
					hostname = val2
				}
			}

			if ip != "" && mac != "" {
				if hostname == "" || hostname == "*" {
					hostname = "Unknown"
				}

				lease := model.ActiveDhcpLease{
					ID:         fmt.Sprintf("lease-%s", mac),
					IPAddress:  ip,
					MacAddress: mac,
					Hostname:   hostname,
					// D-Bus signal doesn't include expire time, we can assume a default or let DB handle it.
					ExpiresIn: "Active",
					ExpiresAt: time.Now().Add(24 * time.Hour).Format(time.RFC3339),
				}

				callback(event, lease)
			}
		}
	}
}
