//go:build linux

package kernel

import (
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"strings"

	"pigate/internal/model"
)

type RealDNSServerManager struct {
	configPath string
}

func NewRealDNSServerManager() *RealDNSServerManager {
	return &RealDNSServerManager{
		configPath: "/etc/dnsmasq.d/pigate-dns.conf",
	}
}

// validateDnsmasqConfig checks configuration syntax using dnsmasq --test
func (m *RealDNSServerManager) validateDnsmasqConfig(tempFile string) error {
	cmd := exec.Command("dnsmasq", "--test", "--conf-file="+tempFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("dnsmasq config validation failed: %s (err: %w)", string(output), err)
	}
	return nil
}

func (m *RealDNSServerManager) ApplyZones(zones []model.DNSZone, interfaces []string, upstreamServers []string, queryLog bool) error {
	log.Printf("[DNS Server] ApplyZones called with %d zones, %d interfaces, %d upstream servers, queryLog=%t", len(zones), len(interfaces), len(upstreamServers), queryLog)

	// Always (re)write the shared base config first. This is the upgrade/ordering
	// guard (Caution 1, issue #50): the base must be `bind-dynamic` before we emit
	// any `interface=` line, otherwise a name referencing a missing link takes down
	// the whole dnsmasq process (DHCP included). Boot ordering already writes the
	// base via DHCP InitApplyConfig, but doing it here too makes every apply safe on
	// its own regardless of what is currently on disk.
	if err := ensureDnsmasqBaseConfig(); err != nil {
		return err
	}

	// The query-log file must exist (and be owned by us) BEFORE dnsmasq starts
	// writing to it, so we can later truncate/rotate it ourselves — see
	// DNSQueryLogPath's doc comment and plan §2 "ให้ pigate สร้างไฟล์ log ล่วงหน้าเอง".
	// Failure here must never block DNS from coming up (log warning only, plan
	// T-05 item 2). When query logging is turned off we remove any previous log
	// file immediately (plan §5 item 1: privacy — turning the switch off erases
	// history right away, not just on next boot).
	if queryLog {
		if f, err := os.OpenFile(DNSQueryLogPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0640); err != nil {
			log.Printf("[DNS Server] Warning: could not pre-create query log file %s: %v", DNSQueryLogPath, err)
		} else {
			f.Close()
		}
	} else {
		if err := os.Remove(DNSQueryLogPath); err != nil && !os.IsNotExist(err) {
			log.Printf("[DNS Server] Warning: could not remove query log file %s: %v", DNSQueryLogPath, err)
		}
	}

	configData := buildDNSConfig(zones, interfaces, upstreamServers, queryLog)

	// Write to temp file for validation
	tempFile := "/tmp/pigate-dns-test.conf"
	if err := os.WriteFile(tempFile, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write temp DNS config: %w", err)
	}
	defer os.Remove(tempFile)

	// Validate syntax
	if err := m.validateDnsmasqConfig(tempFile); err != nil {
		return err
	}

	// Save to production
	if err := os.WriteFile(m.configPath, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write production dnsmasq DNS config: %w", err)
	}

	log.Println("[DNS Server] DNS config applied and validated successfully")
	return m.ReloadConfig()
}

// buildDNSConfig renders the pigate-dns.conf body from the DNS Server settings. It
// is a pure function (no I/O) so the generated directives — including the
// self-healing `interface=` lines — can be unit-tested without touching dnsmasq or
// the filesystem.
func buildDNSConfig(zones []model.DNSZone, interfaces []string, upstreamServers []string, queryLog bool) string {
	var sb strings.Builder
	sb.WriteString("# /etc/dnsmasq.d/pigate-dns.conf — Generated by PiGate\n\n")

	// DNS query-log directives (opt-in, docs/ref/todo/
	// statistics-dns-top-domain-plan.md §2/§5 item 1/item 7): the path is a
	// hardcoded constant, never derived from any input, and log-async batches
	// writes so dnsmasq doesn't block on tmpfs I/O per query. Enabling this
	// moves DNS query (and DHCPACK) activity out of `journalctl -u dnsmasq`
	// into this file instead.
	if queryLog {
		sb.WriteString("# DNS query logging (Statistics: Top Queried Domains) — RAM-only, tmpfs\n")
		sb.WriteString("log-queries\n")
		sb.WriteString(fmt.Sprintf("log-facility=%s\n", DNSQueryLogPath))
		sb.WriteString("log-async=25\n\n")
	}

	// DNS listen interfaces (from DNS Server settings). We emit one `interface=`
	// line per configured name WITHOUT skipping names that don't currently exist —
	// the opposite of the DHCP path. bind-dynamic (see ensureDnsmasqBaseConfig)
	// makes a missing name harmless and binds it automatically if it later appears,
	// so keeping the name in the config is what gives self-healing (Caution 5). Each
	// name is still whitelist-validated as defense-in-depth, because the config
	// import path writes interface names to the DB without validation and a newline
	// could otherwise inject an arbitrary directive (Caution 3).
	if len(interfaces) > 0 {
		sb.WriteString("# DNS listen interfaces (from DNS Server settings)\n")
		for _, name := range interfaces {
			name = strings.TrimSpace(name)
			if name == "" {
				continue
			}
			if err := model.ValidateInterfaceName(name); err != nil {
				log.Printf("[DNS Server] Skipping invalid listen interface %q: %v", name, err)
				continue
			}
			sb.WriteString(fmt.Sprintf("interface=%s\n", name))
		}
		sb.WriteString("\n")
	}

	// Explicit upstream resolvers (either read from System DNS or the DNS
	// Server's own "custom" upstreamServers — see service.resolveUpstreams).
	// We deliberately combine `no-resolv` (ignore /run/dnsmasq/resolv.conf,
	// which is broken on Debian when the resolvconf hook fails) with explicit
	// `server=` lines. Each value is whitelist-validated here as a last line
	// of defense (Caution 3/§5 item 1 of dns-server-settings-tab-and-upstream
	// -plan.md): the config-import path can write these to the DB without
	// going through the handler, and this value is interpolated verbatim into
	// a `server=` directive, so an embedded newline would otherwise inject an
	// arbitrary config line. Filter FIRST, then check len() — only emit
	// `no-resolv` when at least one upstream survives validation; emitting it
	// with zero `server=` lines would leave dnsmasq with no upstream at all
	// (worse than the default, "DNS down for the whole house"). Note:
	// `no-resolv` is process-global, affecting the whole dnsmasq instance
	// (including the DHCP config), which is fine here.
	validUpstreams := make([]string, 0, len(upstreamServers))
	for _, ip := range upstreamServers {
		ip = strings.TrimSpace(ip)
		if ip == "" {
			continue
		}
		if net.ParseIP(ip) == nil {
			log.Printf("[DNS Server] Skipping invalid upstream server %q", ip)
			continue
		}
		validUpstreams = append(validUpstreams, ip)
	}
	if len(validUpstreams) > 0 {
		// Comment text kept identical to the pre-feature string ("from System
		// DNS") so upstreamMode "system" output stays byte-for-byte identical
		// after an upgrade (plan §2 point 1) — it also applies to "custom" now,
		// but changing this line's text isn't worth breaking that guarantee.
		sb.WriteString("# Upstream resolvers (from System DNS)\n")
		sb.WriteString("no-resolv\n")
		for _, ip := range validUpstreams {
			sb.WriteString(fmt.Sprintf("server=%s\n", ip))
		}
		sb.WriteString("\n")
	}

	for _, zone := range zones {
		if !zone.Enabled {
			continue
		}

		zoneName := strings.TrimSpace(zone.ZoneName)
		if zoneName == "" {
			continue
		}

		// Defense-in-depth: never let an un-validated zone reach the config file,
		// even if a malformed value somehow persisted to the DB. The handler and
		// config-import paths reject these up front; this is the last line.
		if err := model.ValidateDNSZone(zone); err != nil {
			log.Printf("[DNS Server] Skipping invalid zone %q: %v", zoneName, err)
			continue
		}

		sb.WriteString(fmt.Sprintf("# Zone: %s\n", zoneName))

		if zone.IsAuthoritative {
			// Mark the zone as local-only. `local=/<zone>/` tells dnsmasq to answer
			// this zone from its own records (host-record/cname/...) and return
			// NXDOMAIN for unknown names instead of forwarding upstream — without
			// putting the whole resolver into authoritative-only mode (which the old
			// `auth-zone=`/`auth-server=` pair did, disabling recursion globally and
			// causing every external query to be REFUSED). `local=/zone/` is a
			// per-zone directive designed to be repeated, so multiple zones coexist
			// (fixes the multi-zone bug). We intentionally do NOT emit `domain=` per
			// zone — that is a global directive already set once in pigate-base.conf.
			sb.WriteString(fmt.Sprintf("local=/%s/\n", zoneName))

			for _, rec := range zone.Records {
				if err := model.ValidateDNSRecord(rec); err != nil {
					log.Printf("[DNS Server] Skipping invalid record %q (type %s) in zone %q: %v", rec.Name, rec.Type, zoneName, err)
					continue
				}

				name := strings.TrimSpace(rec.Name)
				fullName := zoneName
				if name != "" && name != "@" && name != zoneName {
					fullName = fmt.Sprintf("%s.%s", name, zoneName)
				}

				switch strings.ToUpper(rec.Type) {
				case "A", "AAAA":
					// address=/fqdn/ip
					sb.WriteString(fmt.Sprintf("host-record=%s,%s\n", fullName, rec.Value))
				case "CNAME":
					// cname=fqdn,target
					// dnsmasq requires the CNAME target to be a FQDN it can resolve.
					// If the user entered a short name (no dot), treat it as a name
					// within this zone and append the zone name. A value that already
					// contains a dot is treated as a FQDN as-is (trailing dot stripped,
					// since dnsmasq does not use it). We normalize only at generation
					// time — the DB keeps the user's original value untouched.
					target := strings.TrimSuffix(strings.TrimSpace(rec.Value), ".")
					if target != "" && !strings.Contains(target, ".") {
						target = fmt.Sprintf("%s.%s", target, zoneName)
					}
					sb.WriteString(fmt.Sprintf("cname=%s,%s\n", fullName, target))
				case "MX":
					// mx-host=fqdn,target,pref
					pref := "10"
					target := rec.Value
					parts := strings.Fields(rec.Value)
					if len(parts) >= 2 {
						pref = parts[0]
						target = parts[1]
					}
					sb.WriteString(fmt.Sprintf("mx-host=%s,%s,%s\n", fullName, target, pref))
				case "TXT":
					// txt-record=fqdn,"text"
					sb.WriteString(fmt.Sprintf("txt-record=%s,\"%s\"\n", fullName, rec.Value))
				case "PTR":
					// ptr-record=name,fqdn
					sb.WriteString(fmt.Sprintf("ptr-record=%s,%s\n", fullName, rec.Value))
				}
			}
		} else {
			// Forward Zone
			// server=/zone/forward_to
			if zone.ForwardTo != "" {
				sb.WriteString(fmt.Sprintf("server=/%s/%s\n", zoneName, zone.ForwardTo))
			}
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func (m *RealDNSServerManager) ReloadConfig() error {
	return RestartServiceViaDBus("dnsmasq.service")
}

func (m *RealDNSServerManager) ClearCache() error {
	log.Println("[DNS Server] Clearing DNS cache via dnsmasq restart")
	return m.ReloadConfig()
}
