//go:build linux

package kernel

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"pigate/internal/model"
)

type RealDNSServerManager struct {
	configPath string
}

func NewRealDNSServerManager() *RealDNSServerManager {
	return &RealDNSServerManager{
		configPath: "/etc/dnsmasq.d/pigate-dns.conf",
	}
}

// validateDnsmasqConfig checks configuration syntax using dnsmasq --test
func (m *RealDNSServerManager) validateDnsmasqConfig(tempFile string) error {
	cmd := exec.Command("dnsmasq", "--test", "--conf-file="+tempFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("dnsmasq config validation failed: %s (err: %w)", string(output), err)
	}
	return nil
}

func (m *RealDNSServerManager) ApplyZones(zones []model.DNSZone, interfaces []string) error {
	log.Printf("[DNS Server] ApplyZones called with %d zones and %d interfaces", len(zones), len(interfaces))

	var sb strings.Builder
	sb.WriteString("# /etc/dnsmasq.d/pigate-dns.conf — Generated by PiGate\n\n")

	for _, zone := range zones {
		if !zone.Enabled {
			continue
		}

		zoneName := strings.TrimSpace(zone.ZoneName)
		if zoneName == "" {
			continue
		}

		sb.WriteString(fmt.Sprintf("# Zone: %s\n", zoneName))

		if zone.IsAuthoritative {
			sb.WriteString(fmt.Sprintf("auth-zone=%s\n", zoneName))
			if len(interfaces) > 0 {
				nsName := fmt.Sprintf("ns.%s", zoneName)
				sb.WriteString(fmt.Sprintf("auth-server=%s,%s\n", nsName, strings.Join(interfaces, ",")))
			}

			for _, rec := range zone.Records {
				name := strings.TrimSpace(rec.Name)
				fullName := zoneName
				if name != "" && name != "@" && name != zoneName {
					fullName = fmt.Sprintf("%s.%s", name, zoneName)
				}

				switch strings.ToUpper(rec.Type) {
				case "A", "AAAA":
					// address=/fqdn/ip
					sb.WriteString(fmt.Sprintf("host-record=%s,%s\n", fullName, rec.Value))
				case "CNAME":
					// cname=fqdn,target
					sb.WriteString(fmt.Sprintf("cname=%s,%s\n", fullName, rec.Value))
				case "MX":
					// mx-host=fqdn,target,pref
					pref := "10"
					target := rec.Value
					parts := strings.Fields(rec.Value)
					if len(parts) >= 2 {
						pref = parts[0]
						target = parts[1]
					}
					sb.WriteString(fmt.Sprintf("mx-host=%s,%s,%s\n", fullName, target, pref))
				case "TXT":
					// txt-record=fqdn,"text"
					sb.WriteString(fmt.Sprintf("txt-record=%s,\"%s\"\n", fullName, rec.Value))
				case "PTR":
					// ptr-record=name,fqdn
					sb.WriteString(fmt.Sprintf("ptr-record=%s,%s\n", fullName, rec.Value))
				}
			}
		} else {
			// Forward Zone
			// server=/zone/forward_to
			if zone.ForwardTo != "" {
				sb.WriteString(fmt.Sprintf("server=/%s/%s\n", zoneName, zone.ForwardTo))
			}
		}
		sb.WriteString("\n")
	}

	configData := sb.String()

	// Write to temp file for validation
	tempFile := "/tmp/pigate-dns-test.conf"
	if err := os.WriteFile(tempFile, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write temp DNS config: %w", err)
	}
	defer os.Remove(tempFile)

	// Validate syntax
	if err := m.validateDnsmasqConfig(tempFile); err != nil {
		return err
	}

	// Save to production
	if err := os.WriteFile(m.configPath, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write production dnsmasq DNS config: %w", err)
	}

	log.Println("[DNS Server] DNS config applied and validated successfully")
	return m.ReloadConfig()
}

func (m *RealDNSServerManager) ReloadConfig() error {
	return RestartServiceViaDBus("dnsmasq.service")
}

func (m *RealDNSServerManager) ClearCache() error {
	log.Println("[DNS Server] Clearing DNS cache via dnsmasq restart")
	return m.ReloadConfig()
}
