//go:build linux

package kernel

import (
	"strings"
	"testing"

	"pigate/internal/model"
)

// TestBuildDNSConfig_ListenInterfaces covers the self-healing listen-interface
// emission (issue #50): every configured name is emitted (including ones that may
// not exist yet), invalid names are skipped, and an empty list emits no
// `interface=` line at all.
func TestBuildDNSConfig_ListenInterfaces(t *testing.T) {
	t.Run("emits interface line per name without skipping missing ones", func(t *testing.T) {
		cfg := buildDNSConfig(nil, []string{"eth0.301", "wlan1"}, nil, false)
		for _, want := range []string{"interface=eth0.301", "interface=wlan1"} {
			if !strings.Contains(cfg, want) {
				t.Errorf("expected config to contain %q, got:\n%s", want, cfg)
			}
		}
	})

	t.Run("skips invalid names but keeps valid ones", func(t *testing.T) {
		cfg := buildDNSConfig(nil, []string{"eth0", "bad\ninterface=evil", "wlan0"}, nil, false)
		if !strings.Contains(cfg, "interface=eth0") || !strings.Contains(cfg, "interface=wlan0") {
			t.Errorf("expected valid interfaces to be emitted, got:\n%s", cfg)
		}
		if strings.Contains(cfg, "interface=evil") {
			t.Errorf("injected directive must not appear in config, got:\n%s", cfg)
		}
		// The injected directive must not survive on its own line either.
		for _, line := range strings.Split(cfg, "\n") {
			if strings.TrimSpace(line) == "interface=evil" {
				t.Errorf("injection produced a standalone directive line: %q", line)
			}
		}
	})

	t.Run("no interfaces means no interface line", func(t *testing.T) {
		cfg := buildDNSConfig(nil, nil, nil, false)
		if strings.Contains(cfg, "interface=") {
			t.Errorf("expected no interface= line for empty list, got:\n%s", cfg)
		}
	})
}

// TestBuildDNSConfig_ZonesAndUpstreams sanity-checks that the interface refactor
// left the existing zone/upstream rendering intact.
func TestBuildDNSConfig_ZonesAndUpstreams(t *testing.T) {
	zones := []model.DNSZone{
		{
			ZoneName:        "internal.local",
			Enabled:         true,
			IsAuthoritative: true,
			Records: []model.DNSRecord{
				{Name: "www", Type: "A", Value: "192.168.1.10"},
			},
		},
		{
			ZoneName:        "corp.example",
			Enabled:         true,
			IsAuthoritative: false,
			ForwardTo:       "10.0.0.53",
		},
		{
			ZoneName:        "disabled.local",
			Enabled:         false,
			IsAuthoritative: true,
		},
	}
	cfg := buildDNSConfig(zones, []string{"eth0"}, []string{"1.1.1.1"}, false)

	for _, want := range []string{
		"no-resolv",
		"server=1.1.1.1",
		"local=/internal.local/",
		"host-record=www.internal.local,192.168.1.10",
		"server=/corp.example/10.0.0.53",
		"interface=eth0",
	} {
		if !strings.Contains(cfg, want) {
			t.Errorf("expected config to contain %q, got:\n%s", want, cfg)
		}
	}
	if strings.Contains(cfg, "disabled.local") {
		t.Errorf("disabled zone must not be emitted, got:\n%s", cfg)
	}
}

// TestBuildDNSConfig_QueryLogByteIdentical locks in that queryLog=false
// produces byte-for-byte the same config as before this feature existed
// (docs/ref/todo/statistics-dns-top-domain-plan.md T-11 item 12 / §5 item 20)
// — no accidental blank-line/whitespace drift from the new branch.
func TestBuildDNSConfig_QueryLogByteIdentical(t *testing.T) {
	zones := []model.DNSZone{{ZoneName: "internal.local", Enabled: true, IsAuthoritative: true}}
	withoutFeature := "# /etc/dnsmasq.d/pigate-dns.conf — Generated by PiGate\n\n" +
		"# DNS listen interfaces (from DNS Server settings)\ninterface=eth0\n\n" +
		"# Upstream resolvers (from System DNS)\nno-resolv\nserver=1.1.1.1\n\n" +
		"# Zone: internal.local\nlocal=/internal.local/\n\n"

	got := buildDNSConfig(zones, []string{"eth0"}, []string{"1.1.1.1"}, false)
	if got != withoutFeature {
		t.Errorf("queryLog=false must produce byte-identical output to pre-feature config.\nwant:\n%q\ngot:\n%q", withoutFeature, got)
	}
}

// TestBuildDNSConfig_UpstreamValidation covers T-04/T-08 item 5 (🔒): each
// upstream server string is validated with net.ParseIP as a last line of
// defense before being written to `server=<ip>` (defense-in-depth against a
// DB row written directly by config import, bypassing the handler/service
// validators). Malformed values must never appear in the output.
func TestBuildDNSConfig_UpstreamValidation(t *testing.T) {
	t.Run("malformed entries are filtered, valid ones kept", func(t *testing.T) {
		upstreams := []string{
			"1.1.1.1",
			"1.1.1.1\nlog-facility=/etc/x", // newline injection
			"8.8.8.8#5353",                 // port suffix, not a bare IP
			"dns.google",                   // hostname, not an IP
			"8.8.8.8",
		}
		cfg := buildDNSConfig(nil, nil, upstreams, false)

		for _, want := range []string{"server=1.1.1.1", "server=8.8.8.8"} {
			if !strings.Contains(cfg, want) {
				t.Errorf("expected valid upstream %q to be emitted, got:\n%s", want, cfg)
			}
		}
		for _, bad := range []string{
			"log-facility=/etc/x",
			"server=8.8.8.8#5353",
			"server=dns.google",
		} {
			if strings.Contains(cfg, bad) {
				t.Errorf("malformed/injected upstream must not appear in config, found %q in:\n%s", bad, cfg)
			}
		}
		if strings.Count(cfg, "no-resolv") != 1 {
			t.Errorf("expected exactly one no-resolv line when valid upstreams remain, got:\n%s", cfg)
		}
	})

	// Security-critical: no-resolv is process-global and tells dnsmasq to
	// ignore /run/dnsmasq/resolv.conf entirely. If every configured upstream
	// is filtered out but no-resolv is still emitted, dnsmasq is left with
	// ZERO usable upstream — DNS for the whole network breaks (plan §5 item
	// 4). The check must happen AFTER filtering, not before.
	t.Run("all upstreams invalid means no no-resolv line at all", func(t *testing.T) {
		upstreams := []string{
			"1.1.1.1\nlog-facility=/etc/x",
			"not-an-ip",
			"8.8.8.8#5353",
			"   ",
			"",
		}
		cfg := buildDNSConfig(nil, nil, upstreams, false)
		if strings.Contains(cfg, "no-resolv") {
			t.Errorf("no-resolv must NOT appear when every upstream was filtered out (would leave dnsmasq with zero upstreams), got:\n%s", cfg)
		}
		if strings.Contains(cfg, "server=") {
			t.Errorf("expected no server= lines when every upstream was filtered out, got:\n%s", cfg)
		}
	})

	t.Run("empty upstream list means no no-resolv line", func(t *testing.T) {
		cfg := buildDNSConfig(nil, nil, nil, false)
		if strings.Contains(cfg, "no-resolv") {
			t.Errorf("expected no no-resolv line for an empty upstream list, got:\n%s", cfg)
		}
	})
}

// TestBuildDNSConfig_QueryLogDirectives covers the opt-in query-logging
// directives (plan §2) — path is the hardcoded DNSQueryLogPath constant,
// never derived from any input.
func TestBuildDNSConfig_QueryLogDirectives(t *testing.T) {
	cfg := buildDNSConfig(nil, nil, nil, true)
	for _, want := range []string{"log-queries", "log-facility=" + DNSQueryLogPath, "log-async=25"} {
		if !strings.Contains(cfg, want) {
			t.Errorf("expected config to contain %q when queryLog=true, got:\n%s", want, cfg)
		}
	}
}
