//go:build linux

package kernel

import (
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"strings"

	"pigate/internal/model"
)

type RealDNSServerManager struct {
	configPath string
}

func NewRealDNSServerManager() *RealDNSServerManager {
	return &RealDNSServerManager{
		configPath: "/etc/dnsmasq.d/pigate-dns.conf",
	}
}

// validateDnsmasqConfig checks configuration syntax using dnsmasq --test
func (m *RealDNSServerManager) validateDnsmasqConfig(tempFile string) error {
	cmd := exec.Command("dnsmasq", "--test", "--conf-file="+tempFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("dnsmasq config validation failed: %s (err: %w)", string(output), err)
	}
	return nil
}

func (m *RealDNSServerManager) ApplyZones(zones []model.DNSZone, interfaces []string, upstreamServers []string, queryLog bool, blocked []model.BlockedDomain, blocklists []model.BlocklistRef) error {
	log.Printf("[DNS Server] ApplyZones called with %d zones, %d interfaces, %d upstream servers, queryLog=%t, %d blocked domains, %d blocklists", len(zones), len(interfaces), len(upstreamServers), queryLog, len(blocked), len(blocklists))

	// Always (re)write the shared base config first. This is the upgrade/ordering
	// guard (Caution 1, issue #50): the base must be `bind-dynamic` before we emit
	// any `interface=` line, otherwise a name referencing a missing link takes down
	// the whole dnsmasq process (DHCP included). Boot ordering already writes the
	// base via DHCP InitApplyConfig, but doing it here too makes every apply safe on
	// its own regardless of what is currently on disk.
	if err := ensureDnsmasqBaseConfig(); err != nil {
		return err
	}

	// The query-log file must exist (and be owned by us) BEFORE dnsmasq starts
	// writing to it, so we can later truncate/rotate it ourselves — see
	// DNSQueryLogPath's doc comment and plan §2 "ให้ pigate สร้างไฟล์ log ล่วงหน้าเอง".
	// Failure here must never block DNS from coming up (log warning only, plan
	// T-05 item 2). When query logging is turned off we remove any previous log
	// file immediately (plan §5 item 1: privacy — turning the switch off erases
	// history right away, not just on next boot).
	if queryLog {
		// Remove any pre-existing file first. There is no systemd ordering
		// guarantee between pigate.service and the distro's dnsmasq.service
		// (both are independently enabled units), and /run is tmpfs wiped on
		// every reboot — so dnsmasq can win the race and lazily create this
		// path itself on first log write, owned dnsmasq:root, mode 0660.
		// Pigate then can't even open() that file (EACCES, not owner/group),
		// so it would stay wrong-owned forever across every future restart.
		// Pigate DOES own the containing directory (RuntimeDirectory
		// pigate:netdev, 0755, no sticky bit), so unlink is always allowed
		// regardless of the file's own owner — removing it here guarantees
		// the O_CREATE below always produces a fresh, pigate-owned inode.
		if err := os.Remove(DNSQueryLogPath); err != nil && !os.IsNotExist(err) {
			log.Printf("[DNS Server] Warning: could not remove stale query log file %s: %v", DNSQueryLogPath, err)
		}
		if f, err := os.OpenFile(DNSQueryLogPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0640); err != nil {
			log.Printf("[DNS Server] Warning: could not pre-create query log file %s: %v", DNSQueryLogPath, err)
		} else {
			f.Close()
		}
	} else {
		if err := os.Remove(DNSQueryLogPath); err != nil && !os.IsNotExist(err) {
			log.Printf("[DNS Server] Warning: could not remove query log file %s: %v", DNSQueryLogPath, err)
		}
	}

	blocklistDirectives := m.resolveBlocklistDirectives(blocklists)

	configData := buildDNSConfig(zones, interfaces, upstreamServers, queryLog, blocked, blocklistDirectives)

	// Write to temp file for validation
	tempFile := "/tmp/pigate-dns-test.conf"
	if err := os.WriteFile(tempFile, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write temp DNS config: %w", err)
	}
	defer os.Remove(tempFile)

	// Validate syntax
	if err := m.validateDnsmasqConfig(tempFile); err != nil {
		return err
	}

	// Save to production
	if err := os.WriteFile(m.configPath, []byte(configData), 0644); err != nil {
		return fmt.Errorf("failed to write production dnsmasq DNS config: %w", err)
	}

	log.Println("[DNS Server] DNS config applied and validated successfully")
	return m.ReloadConfig()
}

// buildDNSConfig renders the pigate-dns.conf body from the DNS Server settings. It
// is a pure function (no I/O) so the generated directives — including the
// self-healing `interface=` lines — can be unit-tested without touching dnsmasq or
// the filesystem.
func buildDNSConfig(zones []model.DNSZone, interfaces []string, upstreamServers []string, queryLog bool, blocked []model.BlockedDomain, blocklistDirectives []string) string {
	var sb strings.Builder
	sb.WriteString("# /etc/dnsmasq.d/pigate-dns.conf — Generated by PiGate\n\n")

	// DNS query-log directives (opt-in, docs/ref/todo/
	// statistics-dns-top-domain-plan.md §2/§5 item 1/item 7): the path is a
	// hardcoded constant, never derived from any input, and log-async batches
	// writes so dnsmasq doesn't block on tmpfs I/O per query. Enabling this
	// moves DNS query (and DHCPACK) activity out of `journalctl -u dnsmasq`
	// into this file instead.
	if queryLog {
		sb.WriteString("# DNS query logging (Statistics: Top Queried Domains) — RAM-only, tmpfs\n")
		sb.WriteString("log-queries\n")
		sb.WriteString(fmt.Sprintf("log-facility=%s\n", DNSQueryLogPath))
		sb.WriteString("log-async=25\n\n")
	}

	// DNS listen interfaces (from DNS Server settings). We emit one `interface=`
	// line per configured name WITHOUT skipping names that don't currently exist —
	// the opposite of the DHCP path. bind-dynamic (see ensureDnsmasqBaseConfig)
	// makes a missing name harmless and binds it automatically if it later appears,
	// so keeping the name in the config is what gives self-healing (Caution 5). Each
	// name is still whitelist-validated as defense-in-depth, because the config
	// import path writes interface names to the DB without validation and a newline
	// could otherwise inject an arbitrary directive (Caution 3).
	if len(interfaces) > 0 {
		sb.WriteString("# DNS listen interfaces (from DNS Server settings)\n")
		for _, name := range interfaces {
			name = strings.TrimSpace(name)
			if name == "" {
				continue
			}
			if err := model.ValidateInterfaceName(name); err != nil {
				log.Printf("[DNS Server] Skipping invalid listen interface %q: %v", name, err)
				continue
			}
			sb.WriteString(fmt.Sprintf("interface=%s\n", name))
		}
		sb.WriteString("\n")
	}

	// Explicit upstream resolvers (either read from System DNS or the DNS
	// Server's own "custom" upstreamServers — see service.resolveUpstreams).
	// We deliberately combine `no-resolv` (ignore /run/dnsmasq/resolv.conf,
	// which is broken on Debian when the resolvconf hook fails) with explicit
	// `server=` lines. Each value is whitelist-validated here as a last line
	// of defense (Caution 3/§5 item 1 of dns-server-settings-tab-and-upstream
	// -plan.md): the config-import path can write these to the DB without
	// going through the handler, and this value is interpolated verbatim into
	// a `server=` directive, so an embedded newline would otherwise inject an
	// arbitrary config line. Filter FIRST, then check len() — only emit
	// `no-resolv` when at least one upstream survives validation; emitting it
	// with zero `server=` lines would leave dnsmasq with no upstream at all
	// (worse than the default, "DNS down for the whole house"). Note:
	// `no-resolv` is process-global, affecting the whole dnsmasq instance
	// (including the DHCP config), which is fine here.
	validUpstreams := make([]string, 0, len(upstreamServers))
	for _, ip := range upstreamServers {
		ip = strings.TrimSpace(ip)
		if ip == "" {
			continue
		}
		if net.ParseIP(ip) == nil {
			log.Printf("[DNS Server] Skipping invalid upstream server %q", ip)
			continue
		}
		validUpstreams = append(validUpstreams, ip)
	}
	if len(validUpstreams) > 0 {
		// Comment text kept identical to the pre-feature string ("from System
		// DNS") so upstreamMode "system" output stays byte-for-byte identical
		// after an upgrade (plan §2 point 1) — it also applies to "custom" now,
		// but changing this line's text isn't worth breaking that guarantee.
		sb.WriteString("# Upstream resolvers (from System DNS)\n")
		sb.WriteString("no-resolv\n")
		for _, ip := range validUpstreams {
			sb.WriteString(fmt.Sprintf("server=%s\n", ip))
		}
		sb.WriteString("\n")
	}

	for _, zone := range zones {
		if !zone.Enabled {
			continue
		}

		zoneName := strings.TrimSpace(zone.ZoneName)
		if zoneName == "" {
			continue
		}

		// Defense-in-depth: never let an un-validated zone reach the config file,
		// even if a malformed value somehow persisted to the DB. The handler and
		// config-import paths reject these up front; this is the last line.
		if err := model.ValidateDNSZone(zone); err != nil {
			log.Printf("[DNS Server] Skipping invalid zone %q: %v", zoneName, err)
			continue
		}

		sb.WriteString(fmt.Sprintf("# Zone: %s\n", zoneName))

		if zone.IsAuthoritative {
			// Mark the zone as local-only. `local=/<zone>/` tells dnsmasq to answer
			// this zone from its own records (host-record/cname/...) and return
			// NXDOMAIN for unknown names instead of forwarding upstream — without
			// putting the whole resolver into authoritative-only mode (which the old
			// `auth-zone=`/`auth-server=` pair did, disabling recursion globally and
			// causing every external query to be REFUSED). `local=/zone/` is a
			// per-zone directive designed to be repeated, so multiple zones coexist
			// (fixes the multi-zone bug). We intentionally do NOT emit `domain=` per
			// zone — that is a global directive already set once in pigate-base.conf.
			sb.WriteString(fmt.Sprintf("local=/%s/\n", zoneName))

			// NS-delegation (forwarding-based) bookkeeping for this zone
			// (docs/ref/todo/dns-ns-delegation-plan.md T-04). This is
			// forwarding-based delegation, not an authoritative referral:
			// dnsmasq's `local=` is a documented synonym of `server=`, and
			// dnsmasq always picks the longest-matching domain among all
			// server=/local= directives — so a `server=/<sub>/<ip>` line
			// emitted below outranks this zone's own `local=/<zoneName>/`
			// line above for anything under <sub>, causing those queries to
			// be forwarded to <ip> instead of answered/NXDOMAIN'd locally
			// (plan §2.1/§2.2). NS at the zone apex never gets a server=
			// line: forwarding the apex would forward (and override) the
			// ENTIRE zone, including every other record in it (plan §2.5) —
			// that case must go through a Forward Zone instead (also
			// enforced earlier, at the API handler and in the UI).
			existingAddrNames := make(map[string]bool, len(zone.Records))
			for _, ar := range zone.Records {
				t := strings.ToUpper(ar.Type)
				if t != "A" && t != "AAAA" {
					continue
				}
				n := strings.TrimSpace(ar.Name)
				fn := zoneName
				if n != "" && n != "@" && n != zoneName {
					fn = fmt.Sprintf("%s.%s", n, zoneName)
				}
				existingAddrNames[strings.ToLower(fn)] = true
			}
			emittedDelegation := make(map[string]bool)
			emittedGlue := make(map[string]bool)
			delegationHeaderWritten := false

			// Pre-pass (docs/ref/todo/dns-ns-delegation-cname-fix-plan.md
			// T-04 item 1): collect the set of non-apex NS record fullNames
			// using upstream-mode delegation BEFORE the main record loop
			// below, so skipping a colliding glue server= line is
			// deterministic and does NOT depend on the order records happen
			// to appear in zone.Records (Caution 2 — never emit both
			// `server=/x/<ip>` and `server=/x/#` for the same name).
			upstreamDelegatedNames := make(map[string]bool, len(zone.Records))
			for _, ar := range zone.Records {
				if strings.ToUpper(ar.Type) != "NS" {
					continue
				}
				if model.EffectiveNSDelegationMode(ar) != model.DNSNSDelegationModeUpstream {
					continue
				}
				an := strings.TrimSpace(ar.Name)
				afn := zoneName
				if an != "" && an != "@" && an != zoneName {
					afn = fmt.Sprintf("%s.%s", an, zoneName)
				}
				if strings.EqualFold(afn, zoneName) {
					// Apex rows never emit a server= line regardless of mode
					// (the apex guard below rejects them) — don't let one
					// poison this set for other records.
					continue
				}
				upstreamDelegatedNames[strings.ToLower(afn)] = true
			}

			for _, rec := range zone.Records {
				if err := model.ValidateDNSRecord(rec); err != nil {
					log.Printf("[DNS Server] Skipping invalid record %q (type %s) in zone %q: %v", rec.Name, rec.Type, zoneName, err)
					continue
				}

				name := strings.TrimSpace(rec.Name)
				fullName := zoneName
				if name != "" && name != "@" && name != zoneName {
					fullName = fmt.Sprintf("%s.%s", name, zoneName)
				}

				switch strings.ToUpper(rec.Type) {
				case "A", "AAAA":
					// address=/fqdn/ip
					sb.WriteString(fmt.Sprintf("host-record=%s,%s\n", fullName, rec.Value))
				case "CNAME":
					// cname=fqdn,target
					// dnsmasq requires the CNAME target to be a FQDN it can resolve.
					// If the user entered a short name (no dot), treat it as a name
					// within this zone and append the zone name. A value that already
					// contains a dot is treated as a FQDN as-is (trailing dot stripped,
					// since dnsmasq does not use it). We normalize only at generation
					// time — the DB keeps the user's original value untouched.
					target := strings.TrimSuffix(strings.TrimSpace(rec.Value), ".")
					if target != "" && !strings.Contains(target, ".") {
						target = fmt.Sprintf("%s.%s", target, zoneName)
					}
					sb.WriteString(fmt.Sprintf("cname=%s,%s\n", fullName, target))
				case "MX":
					// mx-host=fqdn,target,pref
					pref := "10"
					target := rec.Value
					parts := strings.Fields(rec.Value)
					if len(parts) >= 2 {
						pref = parts[0]
						target = parts[1]
					}
					sb.WriteString(fmt.Sprintf("mx-host=%s,%s,%s\n", fullName, target, pref))
				case "TXT":
					// txt-record=fqdn,"text"
					sb.WriteString(fmt.Sprintf("txt-record=%s,\"%s\"\n", fullName, rec.Value))
				case "PTR":
					// ptr-record=name,fqdn
					sb.WriteString(fmt.Sprintf("ptr-record=%s,%s\n", fullName, rec.Value))
				case "NS":
					// dnsmasq has no dedicated ns-record directive, so publish
					// via the generic dns-rr=<fqdn>,<type>,<hex-rdata> directive
					// (2 = NS), with the target encoded as uncompressed DNS
					// wire format. This only makes dnsmasq ANSWER a direct
					// "type NS" query for fullName — it does NOT delegate
					// queries under the target to another nameserver, and does
					// not create a glue A record.
					target := strings.TrimSuffix(strings.TrimSpace(rec.Value), ".")
					if target != "" && !strings.Contains(target, ".") {
						target = fmt.Sprintf("%s.%s", target, zoneName)
					}
					hex, err := model.EncodeDNSNameHex(target)
					if err != nil {
						log.Printf("[DNS Server] Skipping invalid NS record %q (target %q) in zone %q: %v", rec.Name, rec.Value, zoneName, err)
						continue
					}
					sb.WriteString(fmt.Sprintf("dns-rr=%s,2,%s\n", fullName, hex))

					// Forwarding-based delegation (docs/ref/todo/
					// dns-ns-delegation-plan.md, extended by
					// dns-ns-delegation-cname-fix-plan.md §2/§3 to add a
					// second mode): only for a non-apex NS record that
					// actually wants to forward — mode "glue" (default) with
					// at least one glue IP, or mode "upstream" regardless of
					// glue IPs. A bare publish-only "glue" record with no
					// IPs is a no-op here, so output for every pre-existing
					// record (and every zone not using either feature) is
					// byte-for-byte unchanged.
					mode := model.EffectiveNSDelegationMode(rec)
					if mode == model.DNSNSDelegationModeGlue && len(rec.GlueIPs) == 0 {
						continue
					}
					if strings.EqualFold(fullName, zoneName) {
						// Never at the zone apex, in EITHER mode: forwarding
						// the apex would forward (and override) the ENTIRE
						// zone, including every other record in it. In
						// upstream mode this is worse still — `server=/x/#`
						// at the apex throws the whole zone at the box's
						// normal upstream resolvers, silently discarding
						// every host-record=/cname=/etc. line written above
						// for it (Caution 1). That case must go through a
						// Forward Zone instead (also enforced at the API
						// handler and in the UI).
						log.Printf("[DNS Server] Skipping NS delegation server= for zone-apex record in zone %q (glue IPs are only valid on a non-apex NS record; use a Forward Zone to delegate the whole zone)", zoneName)
						continue
					}

					if !delegationHeaderWritten {
						sb.WriteString("# NS delegation (forwarding-based)\n")
						delegationHeaderWritten = true
					}

					if mode == model.DNSNSDelegationModeUpstream {
						// dnsmasq's `--server` special address '#' means "use
						// the standard servers": `server=/<fqdn>/#` punches a
						// hole through this zone's `local=/<zoneName>/` for
						// just this subtree and hands it to the box's normal
						// upstream resolvers (the `no-resolv` + `server=<ip>`
						// lines written earlier in this function, or
						// /etc/resolv.conf when none are configured). Unlike
						// forwarding straight to the glue IP, those upstreams
						// are real recursive resolvers, so they return a
						// CNAME chain AND its final A/AAAA in one answer from
						// one source — required because dnsmasq refuses to
						// merge records that came from two different sources
						// (a CNAME cannot be answered using a record fetched
						// elsewhere; see dns-ns-delegation-cname-fix-plan.md
						// §2.1/§2.3). We deliberately do NOT also emit the
						// glue server=/x/<ip> lines for this name (§2.4):
						// dnsmasq would pick one of the two per query (or all
						// of them with --all-servers), making answers
						// non-deterministic — worse than either mode alone.
						key := fullName + "|#"
						if !emittedDelegation[key] {
							emittedDelegation[key] = true
							sb.WriteString(fmt.Sprintf("server=/%s/#\n", fullName))
						}
					} else if upstreamDelegatedNames[strings.ToLower(fullName)] {
						// Another NS record for this same fullName is using
						// upstream mode — skip these glue lines rather than
						// emit both variants for the same name (§2.4 above).
						// Upstream mode wins because it is the one capable of
						// returning a complete answer.
						log.Printf("[DNS Server] Skipping glue server= lines for %q in zone %q: already delegated in upstream mode by another NS record", fullName, zoneName)
					} else {
						for _, ip := range rec.GlueIPs {
							parsed := net.ParseIP(ip)
							if parsed == nil || parsed.IsLoopback() || parsed.IsUnspecified() || parsed.IsMulticast() {
								// Defense-in-depth: the same checks as
								// model.ValidateDNSRecord, repeated here in case
								// an invalid value ever reaches the DB via a path
								// that skipped validation — never let it reach
								// the config file (Caution 3).
								log.Printf("[DNS Server] Skipping invalid NS glue IP for %q in zone %q", fullName, zoneName)
								continue
							}
							key := fullName + "|" + ip
							if emittedDelegation[key] {
								continue
							}
							emittedDelegation[key] = true
							sb.WriteString(fmt.Sprintf("server=/%s/%s\n", fullName, ip))
						}
					}

					// Glue host-record for the NS target itself (plan
					// §2.4/§2.6): only when the target name would otherwise
					// NXDOMAIN under this zone's own local= — i.e. it lives
					// in this same parent zone but NOT under the delegated
					// name (that subtree is now served by the delegated
					// nameserver, not by us) — and only if the user hasn't
					// already defined an A/AAAA record for that exact name
					// themselves. Never emit for a target outside this zone
					// (Caution 2 — that would hijack a public name like
					// *.ns.cloudflare.com on the whole LAN's resolver). Runs
					// in BOTH delegation modes: even in upstream mode, the
					// nameserver's own name may still need to resolve
					// locally so the delegated server itself stays
					// reachable.
					lowerTarget := strings.ToLower(target)
					lowerZone := strings.ToLower(zoneName)
					lowerFullName := strings.ToLower(fullName)
					inParentZone := lowerTarget != lowerZone && strings.HasSuffix(lowerTarget, "."+lowerZone)
					underDelegatedName := lowerTarget == lowerFullName || strings.HasSuffix(lowerTarget, "."+lowerFullName)
					if inParentZone && !underDelegatedName && !existingAddrNames[lowerTarget] {
						for _, ip := range rec.GlueIPs {
							parsed := net.ParseIP(ip)
							if parsed == nil || parsed.IsLoopback() || parsed.IsUnspecified() || parsed.IsMulticast() {
								continue
							}
							glueKey := target + "|" + ip
							if emittedGlue[glueKey] {
								continue
							}
							emittedGlue[glueKey] = true
							sb.WriteString(fmt.Sprintf("host-record=%s,%s\n", target, ip))
						}
					}
				}
			}
		} else {
			// Forward Zone
			// server=/zone/forward_to
			if zone.ForwardTo != "" {
				sb.WriteString(fmt.Sprintf("server=/%s/%s\n", zoneName, zone.ForwardTo))
			}
		}
		sb.WriteString("\n")
	}

	// Blocked domains (deny-list, docs/ref/todo/dns-blocked-domains-plan.md
	// §2/§5 item 2): rendered LAST, as its own block, and ONLY when at least
	// one line survives filtering — filter first, then check len(), so an
	// empty/all-skipped deny-list produces byte-for-byte the same output as
	// before this feature existed (Caution 2).
	enabledZoneNames := make(map[string]bool, len(zones))
	for _, zone := range zones {
		if !zone.Enabled {
			continue
		}
		name := strings.TrimSpace(zone.ZoneName)
		if name != "" {
			enabledZoneNames[strings.ToLower(name)] = true
		}
	}

	blockedLines := make([]string, 0, len(blocked))
	for _, b := range blocked {
		if !b.Enabled {
			continue
		}
		// Defense-in-depth: never let an un-validated domain reach the config
		// file, even if a malformed value somehow persisted to the DB. The
		// handler and backup-import paths reject these up front; this is the
		// last line (Caution 1).
		if err := model.ValidateBlockedDomain(b); err != nil {
			log.Printf("[DNS Server] Skipping invalid blocked domain %q: %v", b.Domain, err)
			continue
		}
		// A block target that exactly matches an enabled zone name is
		// ambiguous (Caution 3 — could cut off local name resolution
		// entirely); the handler already rejects this at write time, but skip
		// it here too as a last line of defense.
		if enabledZoneNames[strings.ToLower(b.Domain)] {
			log.Printf("[DNS Server] Skipping blocked domain %q: matches an enabled zone name", b.Domain)
			continue
		}

		mode := b.Mode
		if mode == "" {
			mode = model.DNSBlockModeNXDomain
		}
		switch mode {
		case model.DNSBlockModeSinkhole:
			blockedLines = append(blockedLines,
				fmt.Sprintf("address=/%s/0.0.0.0\n", b.Domain),
				fmt.Sprintf("address=/%s/::\n", b.Domain),
			)
		default: // nxdomain
			blockedLines = append(blockedLines, fmt.Sprintf("server=/%s/\n", b.Domain))
		}
	}
	if len(blockedLines) > 0 {
		sb.WriteString("# Blocked domains (deny-list)\n")
		for _, line := range blockedLines {
			sb.WriteString(line)
		}
		sb.WriteString("\n")
	}

	// Blocklists (bulk import, docs/ref/todo/dns-blocklist-import-plan.md
	// §2.1/§2.7): each entry here is already a complete, ready-to-emit
	// "addn-hosts=<path>" (BlockMode sinkhole) or "conf-file=<path>"
	// (BlockMode nxdomain) directive — the caller (ApplyZones'
	// resolveBlocklistDirectives) has already validated the id and confirmed
	// via os.Stat that the file exists and is non-empty. buildDNSConfig
	// itself does no I/O and must never be handed (or emit) a directive for
	// a path that hasn't been confirmed real (plan Caution 16: a missing
	// conf-file= target makes dnsmasq refuse to start entirely). Filter
	// first (already done by the caller), then check len() here too, so an
	// empty/all-skipped blocklists slice produces byte-for-byte the same
	// output as before this parameter existed (same pattern as
	// blockedLines above).
	if len(blocklistDirectives) > 0 {
		sb.WriteString("# Blocklists (bulk import)\n")
		for _, line := range blocklistDirectives {
			sb.WriteString(line)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// resolveBlocklistDirectives turns enabled blocklist refs into ready-to-emit
// dnsmasq directive lines, confirming via os.Stat that the file each
// directive would reference actually exists and is non-empty before
// including it. A ref that fails id/mode validation, or whose file is
// missing/empty (list added but never fetched/applied yet, or mid-refresh),
// is logged and skipped rather than emitted — see buildDNSConfig's Caution
// 16 note on why a dangling conf-file= reference is unacceptable.
func (m *RealDNSServerManager) resolveBlocklistDirectives(refs []model.BlocklistRef) []string {
	directives := make([]string, 0, len(refs))
	for _, ref := range refs {
		id := strings.TrimSpace(ref.ID)
		if err := model.ValidateDNSBlocklistID(id); err != nil {
			log.Printf("[DNS Blocklist] Skipping blocklist ref with invalid id %q: %v", ref.ID, err)
			continue
		}
		mode, err := model.NormalizeBlocklistBlockMode(ref.BlockMode)
		if err != nil {
			log.Printf("[DNS Blocklist] Skipping blocklist %q with invalid blockMode %q: %v", id, ref.BlockMode, err)
			continue
		}

		var path, directiveName string
		switch mode {
		case model.DNSBlockModeNXDomain:
			path = blocklistConfPath(id)
			directiveName = "conf-file"
		default: // sinkhole
			path = blocklistHostsPath(id)
			directiveName = "addn-hosts"
		}

		fi, err := os.Stat(path)
		if err != nil || fi.Size() == 0 {
			log.Printf("[DNS Blocklist] Skipping blocklist %q (mode=%s): file %s is missing or empty (needs fetch/apply)", id, mode, path)
			continue
		}
		directives = append(directives, fmt.Sprintf("%s=%s", directiveName, path))
	}
	return directives
}

func (m *RealDNSServerManager) ReloadConfig() error {
	return RestartServiceViaDBus("dnsmasq.service")
}

func (m *RealDNSServerManager) ClearCache() error {
	log.Println("[DNS Server] Clearing DNS cache via dnsmasq restart")
	return m.ReloadConfig()
}
