//go:build linux

package kernel

import (
	"fmt"
	"os"
)

// dnsmasqBaseConfigPath is the shared base config both the DHCP and DNS managers
// (re)write. It holds only process-global directives — never per-interface ones —
// since the single dnsmasq instance serves both roles.
const dnsmasqBaseConfigPath = "/etc/dnsmasq.d/pigate-base.conf"

// ensureDnsmasqBaseConfig writes the shared dnsmasq base config, always refreshing
// it so an older on-disk copy (e.g. one still carrying `bind-interfaces` from a
// prior release) is upgraded in place.
//
// It uses `bind-dynamic` rather than `bind-interfaces` on purpose: with
// bind-interfaces, an `interface=<name>` naming a link that does not exist is
// FATAL and takes down the whole dnsmasq process — including DHCP. bind-dynamic
// tolerates missing interfaces (dnsmasq binds them if/when they appear, without a
// restart), which is what lets the DNS Server keep its listen-interface list
// self-healing. `dnsmasq --test` does NOT catch the bind-interfaces failure (it
// only checks syntax), so this base-config choice — not validation — is the real
// safety net. See issue #50.
//
// It is package-level (not a method) so both RealDhcpManager.ApplyConfig and
// RealDNSServerManager.ApplyZones can guarantee an up-to-date base before writing
// their own per-role config, closing the upgrade/ordering trap where a new binary
// emits `interface=` lines while the base is still `bind-interfaces`.
func ensureDnsmasqBaseConfig() error {
	if err := os.MkdirAll("/etc/dnsmasq.d", 0755); err != nil {
		return fmt.Errorf("failed to create dnsmasq.d directory: %w", err)
	}

	// enable-dbus makes dnsmasq own the bus name `uk.org.thekelleys.dnsmasq`
	// on the system bus and emit DhcpLease{Added,Updated,Deleted} signals on every
	// lease change. RealDhcpManager.WatchLeases subscribes to those signals to feed
	// the DHCP lease event log; without this directive dnsmasq never exports to
	// D-Bus, the watcher blocks on a signal that never arrives, and no lease event
	// is ever logged. See issue #67.
	content := `# /etc/dnsmasq.d/pigate-base.conf — Generated by PiGate
domain=pigate.local
expand-hosts
dhcp-authoritative
bind-dynamic
enable-dbus
`
	if err := os.WriteFile(dnsmasqBaseConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write dnsmasq base config: %w", err)
	}
	return nil
}
